version: '3.8'
services:
  zwz-admin-api:
    container_name: zwz-admin-api
    image: vingurzhou/zwz-admin:latest
    privileged: true
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config/:/go-admin-api/config/
      - ./static/:/go-admin-api/static/
      - ./temp/:/go-admin-api/temp/
    networks:
      - backend
  zwz-admin-ui:
    container_name: zwz-admin-ui
    image: vingurzhou/zwz-admin-ui:latest
    privileged: true
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
networks:
  backend:
    driver: bridge

#  docker run -d \
#  --name zwz-admin-api \
#  --privileged \
#  --restart always \
#  -p 8000:8000 \
#  -v ./config/:/go-admin-api/config/ \
#  -v ./static/:/go-admin-api/static/ \
#  -v ./temp/:/go-admin-api/temp/ \
#  --network backend \
#  vingurzhou/zwz-admin:latest
#
#  docker run -d \
#  --name zwz-admin-ui \
#  --privileged \
#  --restart always \
#  -p 80:80 \
#  --network backend \
#  vingurzhou/zwz-admin-ui:latest